ci gitleaks version fix

diff --git a/.github/workflows/build_release.yml b/.github/workflows/build_release.yml
--- a/.github/workflows/build_release.yml
+++ b/.github/workflows/build_release.yml
@@ -51,9 +51,11 @@ jobs:
 #      gitleaks_version: ${{ steps.test-build.outputs.gitleaks_version }}
 
     steps:
-      - name: Check gitleaks version
-        run: echo "Gitleaks version in image is ${{steps.test-build.outputs.gitleaks_version}}"
-        if: ${{ steps.test-build.outputs.gitleaks_version != '' }}
+      - name: Fail if gitleaks version is empty
+        run: |
+          echo "Error: gitleaks_version is empty"
+          exit 1
+        if: ${{ needs.test-build.outputs.gitleaks_version == '' }}
 
       - name: Checkout code
         uses: actions/checkout@v4
@@ -83,7 +85,7 @@ jobs:
             type=raw,value=${{ needs.set_versions.outputs.major_minor }},prefix=
             type=raw,value=${{ needs.set_versions.outputs.major }},prefix=
             type=raw,value=${{ needs.set_versions.outputs.numerical }},prefix=
-            type=raw,value=${{ needs.set_versions.outputs.numerical }}-${{ steps.test-build.outputs.gitleaks_version }},prefix=
+            type=raw,value=${{ needs.set_versions.outputs.numerical }}-${{ needs.test-build.outputs.gitleaks_version }},prefix=
 
           labels: |
             # Standard OCI labels (recommended)
@@ -93,7 +95,7 @@ jobs:
             org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
             org.opencontainers.image.version=${{ steps.set_versions.outputs.numerical }}
             org.opencontainers.image.revision=${{ github.sha }}
-            gitleaks.version=${{ steps.test-build.outputs.gitleaks_version }}
+            gitleaks.version=${{ needs.test-build.outputs.gitleaks_version }}
 
       - name: Build Docker image for publishing
         id: build_image
@@ -122,7 +124,7 @@ jobs:
           README_TEMPLATE_PATH: "README.dockerhub_template.md"
           README_OUTPUT: "README.dockerhub.md"
           VERSION_TAG_PATTERN: "^[0-9]+\\.[0-9]+\\.[0-9]+.*"
-          FULL_VERSION: "${{needs.set_versions.outputs.full}}-${{ steps.test-build.outputs.gitleaks_version }}"
+          FULL_VERSION: "${{needs.set_versions.outputs.full}}-${{ needs.test-build.outputs.gitleaks_version }}"
         run: |
           bash .github/scripts/readme_docker_tag_section.sh
 
